name = "chess-com-rating"
main = "./build/worker.mjs"
compatibility_date = "2024-04-15"
workers_dev = false
preview_urls = false

[vars]
VERCEL_GIT_REPO_SLUG = "chess.com-rating"

[build]
command = "make build"

[observability.logs]
enabled = true

