name = "chess-com-rating"
main = "./main.ts"
compatibility_date = "2025-08-12"
workers_dev = false
preview_urls = false

[build]
command = "pnpm run build"
watch_dir = [ "pkg", "main.go"]

[observability.logs]
enabled = true

